spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:
  thymeleaf:
    cache: false
  mail:
    password:
    host:
    username:
#   QQ邮箱需要开启安全验证
    properties:
      mail:
        stmp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  messages:
    basename: i18n.login
mybatis:
  type-aliases-package: com.system.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
